### ISSUE TITLE
Third dose?

### ISSUE THREAD

**Issue by patabongo** [chris31415926535/covaxr#1]
If I'm searching for booster shots, do I need to specify `doseNumber = 3`? I had to modify the code in order to do that, not that it matters at the moment since there are precisely no appointments available anywhere nearby.

**Comment by chris31415926535** [comment]
`doseNumber = 2` works for me. This is also the parameter that my browser supplies behind the scenes when it's querying the provincial booking system for my third dose. I haven't tested `doseNumber = 3` so I'm not sure what response it would give.

Two points (not documented elsewhere yet):

* For testing, try running the bot for a location that _does_ have some appointments and cross-referencing with what you can see on the provincial booking system: it won't always show the same locations (not sure why) but the appointments should match.
* I built this interface by using Chrome dev tools to inspect the xhr calls my browser made to the provincial API and working backwards--the API is not publicly documented, so if something seems weird feel free to take a look yourself.

**Comment by chris31415926535** [comment]
Also, if you're looking for spots in Ottawa, a bunch of spots just opened up and you can check this live Twitter bot based on this package: https://twitter.com/OttCovidApts

**Comment by patabongo** [comment]
Great! Just booked, thanks.
